
version: '2.3'
services:
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    image: "guti1/azure_ml"
    ports:
      - "8888:8888"
    volumes:
      - .:/app
    command: [ "sh", "-c", "jupyter-lab --ip 0.0.0.0 --port 8888 --allow-root --LabApp.token=''"]